import type { InventoryStockRow } from "@/lib/inventory/types";

/**
 * Realistic demo stock levels for the 15 product names used in mock-data.ts.
 * Deliberately varied to showcase all risk states: critical, warning, healthy, overstock, dead.
 */
export const mockStockRows: InventoryStockRow[] = [
  {
    id: "stock-1",
    user_id: "demo",
    product_name: "Remera oversize negra",
    current_stock: 14,
    reorder_point: 20,
    reorder_quantity: 80,
    supplier_lead_days: 7,
    cost_per_unit: 18,
    external_sku: "RON-001",
    variant_label: null,
    stock_source: "shopify",
    last_synced_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "stock-2",
    user_id: "demo",
    product_name: "Jean straight azul",
    current_stock: 6,
    reorder_point: 15,
    reorder_quantity: 60,
    supplier_lead_days: 10,
    cost_per_unit: 32,
    external_sku: "JSA-002",
    variant_label: null,
    stock_source: "shopify",
    last_synced_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "stock-3",
    user_id: "demo",
    product_name: "Zapatillas urbanas",
    current_stock: 3,
    reorder_point: 10,
    reorder_quantity: 40,
    supplier_lead_days: 14,
    cost_per_unit: 55,
    external_sku: "ZU-003",
    variant_label: null,
    stock_source: "tiendanube",
    last_synced_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "stock-4",
    user_id: "demo",
    product_name: "Hoodie frisa gris",
    current_stock: 45,
    reorder_point: 20,
    reorder_quantity: 60,
    supplier_lead_days: 7,
    cost_per_unit: 28,
    external_sku: "HFG-004",
    variant_label: null,
    stock_source: "manual",
    last_synced_at: null,
    updated_at: new Date().toISOString(),
  },
  {
    id: "stock-5",
    user_id: "demo",
    product_name: "Gorra trucker",
    current_stock: 120,
    reorder_point: 25,
    reorder_quantity: 100,
    supplier_lead_days: 5,
    cost_per_unit: 8,
    external_sku: "GT-005",
    variant_label: null,
    stock_source: "manual",
    last_synced_at: null,
    updated_at: new Date().toISOString(),
  },
  {
    id: "stock-6",
    user_id: "demo",
    product_name: "Buzo canguro verde",
    current_stock: 22,
    reorder_point: 15,
    reorder_quantity: 50,
    supplier_lead_days: 7,
    cost_per_unit: 25,
    external_sku: "BCG-006",
    variant_label: null,
    stock_source: "shopify",
    last_synced_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "stock-7",
    user_id: "demo",
    product_name: "Campera rompevientos",
    current_stock: 8,
    reorder_point: 10,
    reorder_quantity: 30,
    supplier_lead_days: 12,
    cost_per_unit: 42,
    external_sku: "CR-007",
    variant_label: null,
    stock_source: "manual",
    last_synced_at: null,
    updated_at: new Date().toISOString(),
  },
  {
    id: "stock-8",
    user_id: "demo",
    product_name: "Medias pack x3",
    current_stock: 200,
    reorder_point: 50,
    reorder_quantity: 200,
    supplier_lead_days: 3,
    cost_per_unit: 4,
    external_sku: "MP3-008",
    variant_label: null,
    stock_source: "manual",
    last_synced_at: null,
    updated_at: new Date().toISOString(),
  },
  {
    id: "stock-9",
    user_id: "demo",
    product_name: "Riñonera negra",
    current_stock: 0,
    reorder_point: 10,
    reorder_quantity: 40,
    supplier_lead_days: 7,
    cost_per_unit: 12,
    external_sku: "RN-009",
    variant_label: null,
    stock_source: "manual",
    last_synced_at: null,
    updated_at: new Date().toISOString(),
  },
  {
    id: "stock-10",
    user_id: "demo",
    product_name: "Short deportivo",
    current_stock: 35,
    reorder_point: 15,
    reorder_quantity: 60,
    supplier_lead_days: 7,
    cost_per_unit: 14,
    external_sku: "SD-010",
    variant_label: null,
    stock_source: "tiendanube",
    last_synced_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "stock-11",
    user_id: "demo",
    product_name: "Musculosa dry-fit",
    current_stock: 50,
    reorder_point: 20,
    reorder_quantity: 80,
    supplier_lead_days: 5,
    cost_per_unit: 10,
    external_sku: "MDF-011",
    variant_label: null,
    stock_source: "manual",
    last_synced_at: null,
    updated_at: new Date().toISOString(),
  },
  {
    id: "stock-12",
    user_id: "demo",
    product_name: "Mochila urbana",
    current_stock: 18,
    reorder_point: 10,
    reorder_quantity: 30,
    supplier_lead_days: 10,
    cost_per_unit: 35,
    external_sku: "MU-012",
    variant_label: null,
    stock_source: "shopify",
    last_synced_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "stock-13",
    user_id: "demo",
    product_name: "Pantalón chino beige",
    current_stock: 4,
    reorder_point: 10,
    reorder_quantity: 40,
    supplier_lead_days: 10,
    cost_per_unit: 22,
    external_sku: "PCB-013",
    variant_label: null,
    stock_source: "manual",
    last_synced_at: null,
    updated_at: new Date().toISOString(),
  },
  {
    id: "stock-14",
    user_id: "demo",
    product_name: "Camisa linen blanca",
    current_stock: 60,
    reorder_point: 15,
    reorder_quantity: 50,
    supplier_lead_days: 8,
    cost_per_unit: 20,
    external_sku: "CLB-014",
    variant_label: null,
    stock_source: "manual",
    last_synced_at: null,
    updated_at: new Date().toISOString(),
  },
  {
    id: "stock-15",
    user_id: "demo",
    product_name: "Lentes polarizados",
    current_stock: 90,
    reorder_point: 20,
    reorder_quantity: 60,
    supplier_lead_days: 5,
    cost_per_unit: 15,
    external_sku: "LP-015",
    variant_label: null,
    stock_source: "manual",
    last_synced_at: null,
    updated_at: new Date().toISOString(),
  },
];
